### ISSUE TITLE
Test suite failures in network-restricted environments

### ISSUE THREAD

**Issue by kentfredric** [mesalock-linux/mesalink#38]
Under Gentoo's build tooling, network IO can be inhibited/restricted, because its generally viewed dimly that any build-time process can "phone home".

Its also in general bad practice to rely on the availability of network IO, because it makes assertions about your expectations about the build environment ( eg: it could be running on a firewalled / airgapped host ).

The recommendation is to first ascertain if network IO in the *general* sense can be expected to work, before executing tests that inherently require it to give valid output.

```
test libssl::ssl::tests::dummy_openssl_compatible_apis_always_return_success ... ok
test libssl::ssl::tests::get_ssl_fd ... FAILED
test libssl::ssl::tests::get_and_set_ssl_ctx ... ok
test libssl::ssl::tests::invalid_private_key ... ok
test libssl::ssl::tests::legacy_tls_versions_not_supported ... ok
test libssl::ssl::tests::load_verify_locations ... ok
test libssl::ssl::tests::mesalink_ssl_ctx_session_cache_mode_and_size ... ok
test libssl::ssl::tests::mesalink_ssl_set_good_host_name ... ok
test libssl::ssl::tests::mesalink_ssl_set_invalid_host_name ... ok
test libssl::ssl::tests::mesalink_ssl_set_null_host_name ... ok
test libssl::ssl::tests::private_key_not_found ... ok
test libssl::ssl::tests::ssl_ctx_is_not_null ... ok
test libssl::ssl::tests::invalid_certificate ... ok
test libssl::ssl::tests::ssl_ctx_is_thread_safe ... ok
test libssl::ssl::tests::ssl_ctx_load_certificate_and_private_key_asn1 ... ok
test libssl::ssl::tests::ssl_io_on_bad_file_descriptor ... ok
test libssl::ssl::tests::ssl_is_not_null ... ok
test libssl::ssl::tests::ssl_is_thread_safe ... ok
test libssl::ssl::tests::ssl_load_certificate_and_private_key_asn1 ... ok
test libssl::ssl::tests::supported_tls_versions ... ok
test libssl::ssl::tests::test_io_before_full_handshake ... ok
test libssl::ssl::tests::test_null_pointers_as_arguments ... ok
test libssl::ssl::tests::verify_certificate_and_key ... ok
test libssl::ssl::tests::verify_key_and_certificate_1 ... ok
test libssl::ssl::tests::verify_key_and_certificate_2 ... ok
test libssl::x509::tests::x509_null_pointer ... ok
test libssl::ssl::tests::ssl_on_nonblocking_socket ... FAILED
test libssl::ssl::tests::early_data_to_mesalink_io ... FAILED
test libssl::ssl::tests::cross_version_tests ... ok

failures:
---- libssl::ssl::tests::get_ssl_fd stdout ----
thread 'libssl::ssl::tests::get_ssl_fd' panicked at 'Connect error: Os { code: 101, kind: Other, message: "Network is unreachable" }', src/libcore/result.rs:1084:5
stack backtrace:
   0:     0x55813a931de1 - std::sys_common::backtrace::print::hba9498aea52b0a4c
   1:     0x55813a936a12 - std::panicking::default_hook::{{closure}}::h28904950cd69f5ae
   2:     0x55813a93675c - std::panicking::default_hook::h37de51f3afebd886
   3:     0x55813a9370fd - std::panicking::rust_panic_with_hook::hc888d5b8ee53f3c2
   4:     0x55813a936c92 - std::panicking::continue_panic_fmt::h4994c8523413f426
   5:     0x55813a936b76 - rust_begin_unwind
   6:     0x55813a947f7d - core::panicking::panic_fmt::h0f33ccf7fc2a1201
   7:     0x55813a94b627 - core::result::unwrap_failed::h5f2f3948a0c719bd
   8:     0x55813a82d4eb - core::result::Result<T,E>::expect::h6e0dc25503701241
                               at /var/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/src/libcore/result.rs:879
   9:     0x55813a82d4eb - mesalink::libssl::ssl::tests::get_ssl_fd::h0c0f21d37a37c246
                               at src/libssl/ssl.rs:3381
  10:     0x55813a853c2f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h8e266f4baa94b6a7
  11:     0x55813a93794a - __rust_maybe_catch_panic
  12:     0x55813a85f26d - std::sys_common::backtrace::__rust_begin_short_backtrace::h7eec479e3b313f58
  13:     0x55813a8605b5 - std::panicking::try::do_call::h9921ee074f4070c3
  14:     0x55813a93794a - __rust_maybe_catch_panic
  15:     0x55813a865cd2 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf525dbe56a508edf
  16:     0x55813a93451f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h4c1084bf7672115a
  17:     0x55813a9377a0 - std::sys::unix::thread::Thread::new::thread_start::h9505cc4fd13f1815
  18:     0x7f36abd683a7 - start_thread
                               at /var/tmp/portage/sys-libs/glibc-2.29-r5/work/glibc-2.29/nptl/pthread_create.c:486
  19:     0x7f36abc7d0ff - __clone
  20:                0x0 - <unknown>

---- libssl::ssl::tests::early_data_to_mesalink_io stdout ----
thread 'libssl::ssl::tests::early_data_to_mesalink_io' panicked at 'Failed to connect: Custom { kind: Other, error: "failed to lookup address information: Temporary failure in name resolution" }', src/libcore/result.rs:1084:5
stack backtrace:
   0:     0x55813a931de1 - std::sys_common::backtrace::print::hba9498aea52b0a4c
   1:     0x55813a936a12 - std::panicking::default_hook::{{closure}}::h28904950cd69f5ae
   2:     0x55813a93675c - std::panicking::default_hook::h37de51f3afebd886
   3:     0x55813a9370fd - std::panicking::rust_panic_with_hook::hc888d5b8ee53f3c2
   4:     0x55813a936c92 - std::panicking::continue_panic_fmt::h4994c8523413f426
   5:     0x55813a936b76 - rust_begin_unwind
   6:     0x55813a947f7d - core::panicking::panic_fmt::h0f33ccf7fc2a1201
   7:     0x55813a94b627 - core::result::unwrap_failed::h5f2f3948a0c719bd
   8:     0x55813a82eead - core::result::Result<T,E>::expect::h6e0dc25503701241
                               at /var/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/src/libcore/result.rs:879
   9:     0x55813a82eead - mesalink::libssl::ssl::tests::early_data_to_mesalink_io::h348b7703c02fa9aa
                               at src/libssl/ssl.rs:3550
  10:     0x55813a853c2f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h8e266f4baa94b6a7
  11:     0x55813a93794a - __rust_maybe_catch_panic
  12:     0x55813a85f26d - std::sys_common::backtrace::__rust_begin_short_backtrace::h7eec479e3b313f58
  13:     0x55813a8605b5 - std::panicking::try::do_call::h9921ee074f4070c3
  14:     0x55813a93794a - __rust_maybe_catch_panic
  15:     0x55813a865cd2 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf525dbe56a508edf
  16:     0x55813a93451f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h4c1084bf7672115a
  17:     0x55813a9377a0 - std::sys::unix::thread::Thread::new::thread_start::h9505cc4fd13f1815
  18:     0x7f36abd683a7 - start_thread
                               at /var/tmp/portage/sys-libs/glibc-2.29-r5/work/glibc-2.29/nptl/pthread_create.c:486
  19:     0x7f36abc7d0ff - __clone
  20:                0x0 - <unknown>

---- libssl::ssl::tests::ssl_on_nonblocking_socket stdout ----
thread 'libssl::ssl::tests::ssl_on_nonblocking_socket' panicked at 'Conenction failed: Custom { kind: Other, error: "failed to lookup address information: Temporary failure in name resolution" }', src/libcore/result.rs:1084:5
stack backtrace:
   0:     0x55813a931de1 - std::sys_common::backtrace::print::hba9498aea52b0a4c
   1:     0x55813a936a12 - std::panicking::default_hook::{{closure}}::h28904950cd69f5ae
   2:     0x55813a93675c - std::panicking::default_hook::h37de51f3afebd886
   3:     0x55813a9370fd - std::panicking::rust_panic_with_hook::hc888d5b8ee53f3c2
   4:     0x55813a936c92 - std::panicking::continue_panic_fmt::h4994c8523413f426
   5:     0x55813a936b76 - rust_begin_unwind
   6:     0x55813a947f7d - core::panicking::panic_fmt::h0f33ccf7fc2a1201
   7:     0x55813a94b627 - core::result::unwrap_failed::h5f2f3948a0c719bd
   8:     0x55813a82ba26 - core::result::Result<T,E>::expect::h6e0dc25503701241
                               at /var/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/src/libcore/result.rs:879
   9:     0x55813a82ba26 - mesalink::libssl::ssl::tests::ssl_on_nonblocking_socket::h1483b5459a0c207e
                               at src/libssl/ssl.rs:3037
  10:     0x55813a853c2f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h8e266f4baa94b6a7
  11:     0x55813a93794a - __rust_maybe_catch_panic
  12:     0x55813a85f26d - std::sys_common::backtrace::__rust_begin_short_backtrace::h7eec479e3b313f58
  13:     0x55813a8605b5 - std::panicking::try::do_call::h9921ee074f4070c3
  14:     0x55813a93794a - __rust_maybe_catch_panic
  15:     0x55813a865cd2 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf525dbe56a508edf
  16:     0x55813a93451f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h4c1084bf7672115a
  17:     0x55813a9377a0 - std::sys::unix::thread::Thread::new::thread_start::h9505cc4fd13f1815
  18:     0x7f36abd683a7 - start_thread
                               at /var/tmp/portage/sys-libs/glibc-2.29-r5/work/glibc-2.29/nptl/pthread_create.c:486
  19:     0x7f36abc7d0ff - __clone
  20:                0x0 - <unknown>


failures:
    libssl::ssl::tests::early_data_to_mesalink_io
    libssl::ssl::tests::get_ssl_fd
    libssl::ssl::tests::ssl_on_nonblocking_socket

test result: FAILED. 61 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by kentfredric** [comment]
FWIW, I'm just locally applying this patch for now, as nothing sets feature = "network_tests" ( and it shouldn't be a feature visible on the crate, in case you feel like re-using this ).

```patch
diff --git a/src/libssl/ssl.rs b/src/libssl/ssl.rs
index f5e0080..9eb905b 100644
--- a/src/libssl/ssl.rs
+++ b/src/libssl/ssl.rs
@@ -3033,6 +3033,7 @@ mod tests {
     }
 
     #[test]
+    #[cfg(feature = "network_tests")]
     fn ssl_on_nonblocking_socket() {
         let sock = net::TcpStream::connect("mesalink.io:443").expect("Conenction failed");
         assert_eq!(true, sock.set_nonblocking(true).is_ok());
@@ -3375,6 +3376,7 @@ mod tests {
     }
 
     #[test]
+    #[cfg(feature = "network_tests")]
     fn get_ssl_fd() {
         let ctx_ptr = mesalink_SSL_CTX_new(mesalink_TLS_client_method());
         let ssl_ptr = mesalink_SSL_new(ctx_ptr);
@@ -3525,6 +3527,7 @@ mod tests {
     }
 
     #[test]
+    #[cfg(feature = "network_tests")]
     fn early_data_to_mesalink_io() {
         const HTTP_REQUEST: &[u8; 83] = b"GET / HTTP/1.1\r\n\
             Host: mesalink.io\r\n\
```

**Comment by ymjing** [comment]
Thanks for the update. This is WAI. Closing for now.
